name: Build and Publish NuGet Package

on:
  push:
    tags:
      - 'v*'
    branches:
      - main  

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore src/HangfireJobsKit/HangfireJobsKit.csproj

      - name: Build
        run: dotnet build src/HangfireJobsKit/HangfireJobsKit.csproj --configuration Release --no-restore

      # Skip tests for now since test project isn't ready yet
      #- name: Test
      #  run: dotnet test --configuration Release --no-build

      - name: Package
        run: dotnet pack src/HangfireJobsKit/HangfireJobsKit.csproj --configuration Release --no-build --output nupkg
      
      - name: Publish to NuGet.org
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json